export const categories = [
  {
    id: "0",
    title: "Tarihi Yapılar",
    category_name: "tarihi_yapilar",
    image: "src/assets/tarihi_yapilar/meramkoprusu-1.jpg",
    sub_categories: [
      {
        id: "0",
        title: "Aziz Pavlus Kilisesi",
        image: "src/assets/tarihi_yapilar/kilistra_kilise1.jpg",
      },
      {
        id: "1",
        title: "Kilistra Haçlı (Kaya) Kilise",
        image: "",
      },
      {
        id: "2",
        title: "Kilistra Antik Kenti,",
        image: "",
      },
      {
        id: "3",
        title: "Ağustos Oteli",
        image: "",
      },
      {
        id: "4",
        title: "Meram Köprüsü",
        image: "",
      },
      {
        id: "5",
        title: "Tantavi Hanı",
        image: "",
      },
    ],
  },
  {
    id: "1",
    title: "Camiler ve Medreseler",
    category_name: "camiler",
    image: "src/assets/camiler/kapu-cami-1.jpg",
    sub_categories: [
      {
        id: "0",
        title: "Kapu Camii",
        image: "src/assets/camiler/kapu-cami-1.jpg",
      },
      {
        id: "1",
        title: "İplikçi Cami",
        image: "",
      },
      {
        id: "2",
        title: "Sahip Ata Camii ve Külliyesi",
        image: "",
      },
      {
        id: "3",
        title: "Sırçalı Medrese",
        image: "",
      },
      {
        id: "4",
        title: "Tavus Baba Türbesi",
        image: "",
      },
      {
        id: "5",
        title: "Nasuh Bey Camii ve Darul Huffazı",
        image: "",
      },
    ],
  },
  {
    id: "2",
    title: "Parklar",
    category_name: "park",
    image: "src/assets/parklar/80-binde-devri-alem-1.jpg",
    sub_categories: [
      {
        id: "0",
        title: "80 Binde Devri Alem",
        image: "",
      },
      {
        id: "1",
        title: "Berlika Trafik Eğitim Parkı",
        image: "",
      },
      {
        id: "2",
        title: "Dutlukır Millet Bahçesi",
        image: "",
      },
      {
        id: "3",
        title: "Karaaslan Piknik Alanı",
        image: "",
      },
      {
        id: "4",
        title: "Hadimi Parkı",
        image: "",
      },
    ],
  },
  {
    id: "3",
    title: "Doğa",
    category_name: "doga",
    image: "src/assets/doga/meramkentormani-2.jpg",
    sub_categories: [
      {
        id: "0",
        title: "Meram Kent Ormanı",
        image: "",
      },
      {
        id: "1",
        title: "Meram Çayı",
        image: "",
      },
      {
        id: "2",
        title: "Meram Bağ ve Bahçeleri",
        image: "",
      },
      {
        id: "3",
        title: "Tavus Baba Koruluğu",
        image: "",
      },
      {
        id: "4",
        title: "Kızlar Kayası",
        image: "",
      },
    ],
  },
  {
    id: "4",
    title: "Müzeler",
    category_name: "muze",
    image: "src/assets/muze/ataturkmuzesi-1.jpg",
    sub_categories: [
      {
        id: "0",
        title: "Etnografya Müzesi",
        image: "",
      },
      {
        id: "1",
        title: "Sahip Ata Vakıf Müzesi",
        image: "",
      },
      {
        id: "2",
        title: "Atatürk Evi",
        image: "",
      },
    ],
  },
];


export const details = [
  {
    id: "0",
    sub_category: "Parklar",
    sub_category_name: "park",
    title: "80 Binde Devri Alem Parkı",
    path: "80BindeDevriAlem",
    cover_image:"/src/assets/parklar/80-binde-devri-alem-1.jpg",
    description:
      "80 Binde Devri Alem Parkı bünyesinde üç farklı konsept bulunduruyor. Bu haliyle Türkiye’de bir ilk olma özelliği taşıyan parkta 120 minyatür eser ile 50 hareketli ve sesli dinozor bulunuyor. Minyatür eserler arasında Bosna Hersek’te bulunan Mostar Köprüsü’nden İstanbul’un simge eserleri Haydarpaşa Garı, Kız Kulesi ve Ayasofya Camii’ne, Buhara’da bulunan 10 bin kişilik Kalon Camii’nin minyatürüne kadar 120 adet eserin minyatürleri sergileniyor.Dinozor parkında ise kanat açıklığı 7 metreye kadar ulaşabilen kanatlı kertenkele ‘Pterosaur’, en büyük silahı kuyruğunun ucundaki sert topuz şeklindeki kemik olan ‘Ankylosaurus’, bilinen en büyük etoburlar ‘TRex’ ve ‘Spinosaurus’ ile boyu 45 metre kilosu 90 tona ulaşabilen dev otobur ‘Seismosaurus’ gibi dinozor maketleri ziyaretçilerini tarih öncesi bir yolculuğa çıkarıyor. Cihanı Türk Abideler Şehri Bölümü’nde ise bin yıllık devlet geleneğimiz ile mimari ve sanat anlayışımızla hayat bulan eserler sergileniyor. Pamuk Şekeri Masal Dünyası Parkı’nda ise çizgi ve hayal kahramanlarından Hacivat Karagöz, Nasreddin Hoca gibi pek çok isim tanıtılıyor. Parkta ailelerin de dinlenebilmeleri içinde farklı seçenekler sunuluyor.",
    image1:"/src/assets/parklar/80-binde-devri-alem-1.jpg",
    image2:"/src/assets/parklar/80-binde-devri-alem-2.jpg",
    image3:"/src/assets/parklar/80-binde-devri-alem-3.jpg",
    image4:"/src/assets/parklar/80-binde-devri-alem-4.jpg",
  },
  {
    id: "1",
    sub_category: "Parklar",
    sub_category_name: "park",
    title: "Berlika Trafik Eğitim Parkı",
    path: "berlikaparki",
    cover_image:"/src/assets/parklar/berlika1.jpg",
    description:
      "2014 yılında yapımı tamamlanan Berlika Parkı içerisinde bulunan eğlence alanı revize edilmiştir. Bu revize sonucunda 3500 m²’ lik alan çocuklara yönelik trafik eğitim parkı olarak tasarlanmış olup halkımızın hizmetine sunulmuştur. Revizyon Kapsamında; Basketbol ve voleybol saha tellerinin yenileme ve bakımı, 1930 m² koşu yolunun bakımı, Kafeterya binasının restorasyonu, 1111 m² asfalt serimi yapılmıştır. Peyzaj çalışması olarak 45 adet ağaç, 160 adet gül ve 10.146 adet çalı türü dikilmiş ve trafik eğitim parkı içerisine 500 m² çim ekimi yapılmıştır.",
    image1:"/src/assets/parklar/berlika1.jpg",
    image2:"/src/assets/parklar/berlika2.jpg",
    image3:"/src/assets/parklar/berlika3.jpg",
    image4:"/src/assets/parklar/berlika4.jpg",
    
  },
  {
    id: "2",
    sub_category: "Parklar",
    sub_category_name: "park",
    title: "Dutlukır Millet Bahçesi",
    path: "dutlukir",
    cover_image:"/src/assets/parklar/dutlukir1.jpg",
    description:
      "Konya adına birçok ilki bünyesinde barındıran Millet Bahçesi, çok amaçlı alanlardan oluşuyor. Misafirlerine Meram’ın muhteşem havası ve yeşilliğinde, ateşli ya da ateşsiz alanlarda piknik yapabilme imkanı sunan bahçe, bunun yanı sıra yürüyüş ve spor alanları, restoran ve kafesi, çim kızağı ve parklarıyla verdiği hizmetlerin yanı sıra sosyal ve kültürel birçok etkinliğe de ev sahipliği yapıyor. Çok yönlü hizmet veren Dutlukır Millet Bahçesinde ayrıca, 100 adet çocuk oyun grubu, 40 bin metrekarelik çocuk oyun parkı, 10 bin metrekarelik üzüm bağı, 10 bin metrekarelik bir gölet, Osmanlı Bahçesi, mescit, sosyal tesisler, kokuluk ve reçellik gül bahçesi gibi renkli ve ilgi çekici alanlar bulunuyor.",
    image1:"/src/assets/parklar/dutlukir1.jpg",
    image2:"/src/assets/parklar/dutlukir2.jpg",
    image3:"/src/assets/parklar/dutlukir3.jpg",
    image4:"/src/assets/parklar/dutlukir4.jpg",
  },
  {
    id: "3",
    sub_category: "Parklar",
    sub_category_name: "park",
    title: "Karaaslan Piknik Alanı",
    path: "karaaslan",
    cover_image:"/src/assets/parklar/karaaslan1.jpg",
    description:
      "Karaaslan Hobi Bahçelerinin yanı başında 97.500 m²’lik alanda yer alan Karaaslan Piknik Bahçesi 100'er metrekarelik 454 adet piknik bahçesinin yer aldığı yeni konseptte; mangal yeri, kamelya, lavabo ve peyzaj bitkileri, ortak alanlarda ise fitness ve çocuk oyun alanı mescit gibi sosyal donatı alanları ile ailenizle birlikte güzel bir gün geçirmeniz için her şey düşünüldü.",
    image1:"/src/assets/parklar/karaaslan1.jpg",
    image2:"/src/assets/parklar/karaaslan2.jpg",
    image3:"/src/assets/parklar/karaaslan3.jpg",
    image4:"/src/assets/parklar/karaaslan4.jpg",
  },

  {
    id: "4",
    sub_category: "Parklar",
    sub_category_name: "park",
    title: "Hadimi Parkı",
    path: "hadimi",
    cover_image:"/src/assets/parklar/hadimi1.jpg",
    description:
      "Konya Büyükşehir Belediyesi tarafından yaptırılan, 186 bin m² alanı ile Konya’nın en büyük parkı olan Karaaslan Hadimi Parkı Yaylapınar Mahallesi’nde yer alıyor. 128 bin m² yeşil alan ve Türkiye’de ilk kez bir parkta 15 bin m²’lik meyve bahçesi yer alıyor. Parka gelenlere meyve toplama imkânı sunuluyor. Engellilerin de kullanımına uygun yapılan Karaaslan Hadimi Parkı’nda piknik alanlarının yanı sıra; 7 bin m²’lik gölet ve havuz grupları, 15 bin m²’lik meyve bahçesi, atlı binicilik tesisi, kapalı oturma alanları, lunapark, çocuk oyun grupları, basketbol sahaları, tenis kortu ve sergi alanları yer alıyor.",
    image1:"/src/assets/parklar/hadimi1.jpg",
    image2:"/src/assets/parklar/hadimi2.jpg",
    image3:"/src/assets/parklar/hadimi3.jpg",
    image4:"/src/assets/parklar/hadimi4.jpg",
  },

  {
    id: "5",
    sub_category: "Doğa",
    sub_category_name: "doga",
    title: "Konya Kent Ormanı",
    path: "kent_ormani",
    cover_image:"/src/assets/doga/meramkentormani-2.jpg",
    description:
      "Meram ilçesi sınırları içerisinde yer alan Konya Kent Ormanı’na giriş ücretsizdir. Kent Ormanı, Konya Büyükşehir Belediyesi’nin yeşil alan miktarını artırmaya yönelik projesi çerçevesinde, Orman Genel Müdürlüğü’nden işletme hakkını on yıllığına devraldığı orman arazisini düzenlenmesi sonucunda tesis edilmiştir. Kent Ormanı Parkı Konya Büyükşehir Belediyesi tarafından 5.270.000 m² genişliğindeki ormanlık bölgede çeşitli sosyal tesisler yapılarak 2005 yılında hizmete açılmıştır. Yürütülen çalışmalar kapsamında 5,5 hektarlık mesire alanı içerisinde 5 kilometre uzunluğunda asfalt yollar ile göletler, doğal yürüyüş parkurları, kamelyalar, oturma bankları, futbol ve basketbol sahaları, seyir terasları, mescit, otopark ve çeşmeler yapılmıştır. Kentin akciğerleri durumunda olan Konya Kent Ormanı’nda 2004 yılında kurulan güneş enerjili aydınlatma sistemi ile güneş ışığından elektrik üretilmekte ve bu üretim iki adet rüzgârgülü ile desteklenmektedir. Gündüzleri güneş enerjisi panelleriyle elde edilen elektrik elliye yakın aküde toplanarak, geceleri parkın sokak lambalarıyla aydınlatılması, sosyal tesis ve bekçi kulübelerindeki elektronik eşyaların çalıştırılmasında kullanılmaktadır. Bu sistemle Kent Ormanı Parkı’ndaki elektrik ihtiyacı yaz-kış kesintisiz olarak karşılanmaktadır.",
    image1:"/src/assets/doga/meramkentormani.jpg",
    image2:"/src/assets/doga/meramkentormani-2.jpg",
    image3:"/src/assets/doga/meramkentormani-3.jpg",
    image4:"/src/assets/doga/meramkentormani-4.jpg",
  },
  {
    id: "6",
    sub_category: "Doğa",
    sub_category_name: "doga",
    title: "Kızlar Kayası",
    path: "kizlar_kayasi",
    cover_image:"/src/assets/doga/kizlar_kayasi4.jpg",
    description:
      "Meram Belediyesi tarafından gerçekleştirilen çevre düzenlemesiyle turizme kazandırılan Kızlar Kayası, yerli ve yabancı turistlerin ilgi odağı haline geldi. Vatandaşların aileleri ve dostlarıyla sıcak yaz akşamlarında huzurlu vakit geçirdiği Kızlar Kayası, nişanlı çiftlerin evlilik teklifi gibi renkli organizasyonlarıyla da tarifsiz anlara şahitlik ediyor.. Kızlar Kayası’nın da içerisinde bulunduğu Meram’ın yeni turizm rotasyonu hakkında da bilgi veren Başkan Kavuş şunları söyledi; “Ayrıca Meram Bağı ile başlayarak Meram Millet Bahçesi’ne kadar uzanan 1,5 kilometre çap aralığındaki tarih, turizm ve kültür rotasyonu Meram’a çok yakışacak. Kızlar Kayası’nın da bulunduğu rotada yer alan Meram Bağı, Lavanta Bahçesi, Kızlar Kayası, Meram Köprüsü, Tavusbaba, Aydın Çavuş, 80 Binde Devri Alem Parkı ve Meram Millet Bahçesi şehrimize gelen misafirlerimiz için çok farklı ve doyumsuz bir destinasyon olacak. Tarihi ve doğasıyla Evliya Çelebi’nin Seyahatnamesi’nde övgüyle bahsettiği Meram, eşsiz güzelliğiyle nam salmaya devam edecek’",
    image1:"/src/assets/doga/kizlar_kayasi1.jpg",
    image2:"/src/assets/doga/kizlar_kayasi2.jpg",
    image3:"/src/assets/doga/kizlar_kayasi3.jpg",
    image4:"/src/assets/doga/kizlar_kayasi4.jpg",
  },
  {
    id: "7",
    sub_category: "Doğa",
    sub_category_name: "doga",
    title: "Tavus Baba Koruluğu",
    path: "tavus_baba_korulugu",
    cover_image:"/src/assets/doga/tavus_baba1.jpg",
    description: "",
    image1:"/src/assets/doga/tavus_baba1.jpg",
    image2:"/src/assets/doga/tavus_baba2.jpg",
    image3:"/src/assets/doga/tavus_baba3.jpg",
    image4:"/src/assets/doga/tavus_baba4.jpg",
  },
  {
    id: "8",
    sub_category: "Doğa",
    sub_category_name: "doga",
    title: "Meram Bağ ve Bahçeleri",
    path: "meram_bagi",
    cover_image:"/src/assets/doga/meram_bagi1.jpg",
    description:
      "Konya’ya ilahi bir lütuf olan yeşillikler denizi Meram meşhur piknik, gezinti ve dinlenme yerlerinin başında gelir. Eskiden “Türbe önünde evi, Meram da bağı olmak” meşhur sözü her Konyalının gönlünü süsleyen bir arzu idi. İlkbaharda insanlar Meram konak ve köşklerine taşınır, sonbaharın sonunda şehir evine dönerlerdi. Şehre 6 km mesafededir. Temiz ve serin havası, tertemiz suyu yemyeşil toprağı ile cennetten bir köşe gibidir. Selçuklulardan beri durumu elverişli olanlar yazın Meram’daki ev, konak ve köşküne taşınırlar. Bağ evlerinde misafirler ağırlanır. Hititlerden beri bilinen bu yeşil vadi, gerçek güzelliğini, dillere destan görünümünü Selçuklular, Karamanoğulları ve Osmanlı zamanında elde etmiştir. Yazın sıcağında serin serin esen meşhur rüzgârının adı ‘Gedavet’ (Gedâ-Bâd)dir.",
    image1:"/src/assets/doga/meram_bagi1.jpg",
    image2:"/src/assets/doga/meram_bagi2.jpg",
    image3:"/src/assets/doga/meram_bagi3.jpg",
    image4:"/src/assets/doga/meram_bagi4.jpg",
  },
  {
    id: "9",
    sub_category: "Doğa",
    sub_category_name: "doga",
    title: "Meram Çayı",
    path: "meram_cayi",
    cover_image:"/src/assets/doga/meram_cayi1.jpg",
    description:
      "Rivayete göre Meram’ı Meram yapan güzelliklerin iki sebebi vardır. Bunlardan biri, Meram Çayı ikincisi de halkın Gedavet adını verdiği serin Meram rüzgârıdır. Konya’ya hayat veren Meram Deresi, şehrin batısındaki dağlardan doğan; Başarakavak, Sille ve Dere sularını toplayan Altınapa Barajı’ndan kaynağını alır ve yolculuğunda önemli oranda su kaybetse de şehrin içinden geçerek doğudaki Aslım Bataklığı’na kadar ulaşır. Kapalı bir havzadan su toplayan Meram Çayı, 630 km² bir alanda Aladağ, Gevele, Kalburcu, Karganlıdağ, Kocaçal, Loras Dağı, Meke, Salahaddin, Şalgamlık, Uğurca yörelerinden beslenmektedir. Akış yönü boyunca ilçe sınırlarında meyve bahçelerini sulayan Meram Deresi’nin etrafında gövdelerini 2-3 kişinin ancak sarabildiği devasa söğütler ve iğde ağaçları boy gösterir. Meram Çayı’nın en güzel görüldüğü yerlerden biri Meram son durak adıyla bilinen mevkidir. Burası etrafındaki yeşillikler, çay bahçeleri, piknik alanları ve dinlenme tesislerinden oluşan ünlü bir mesire yeridir. Yazın en sıcak günlerinde dahi serin, esintili ve çam kokulu havası, berrak akarsuyu, nefis gül bahçeleri ve yemyeşil ormanlık alanlarıyla yerli ve yabancı misafirler için vazgeçilmezdir. Burada gezinti tekneleri ile güzel vakitler geçirebilir, yöresel lezzetleri tadabilir ve Konya’nın güzelliklerini göstermek hususunda oldukça cömert olan Aydın Çavuş Tepesi’ne çıkarak tüm Konya’yı kanatlarınızın altında kuşbakışı izleyebilirsiniz.",
    image1:"/src/assets/doga/meram_cayi1.jpg",
    image2:"/src/assets/doga/meram_cayi2.jpg",
    image3:"/src/assets/doga/meram_cayi3.jpg",
    image4:"/src/assets/doga/meram_cayi4.jpg",
  },
  {
    id: "10",
    sub_category: "Tarihi Yapılar",
    sub_category_name: "tarihi_yapilar",
    title: "Aziz Pavlus Kilisesi",
    path: "azizpavlus_kilisesi",
    cover_image:"/src/assets/tarihi_yapilar/azizpavlus_kilisesi1.jpg",
    description:
      "Konya’nın meşhur Alâeddin Tepesi’nin güneyinde yer alan ve Assumpsyonist rahipler tarafından inşa ettirilen bu Roma Katolik kilisesi, Konya’ya özgü kesme sille taşıyla örülüp 1910 yılında tamamlanmıştır. Mayasını böylece şehrin taşından ve toprağından alan kilise, hoşgörü üzerine temellendirilen büyük tasavvuf geleneğinin somut bir örneği olarak günümüze ulaşmıştır. Gotik üslûptaki cephesiyle yoğun ilgi gören kilise, ilk misyonerlik gezisi kapsamında Konya’yı ziyaret eden Aziz Pavlus’un geçtiği yer ve yöreleri görmek isteyen Hristiyan topluluklar tarafından sıklıkla ziyaret edilmekte ve adını da bu azizden almaktadır. Kilisede, ziyaretçileri bilgilendirmek üzere İtalya’dan gelen bir din adamı bulunmaktadır.",
    image1:"/src/assets/tarihi_yapilar/azizpavlus_kilisesi1.jpg",
    image2:"/src/assets/tarihi_yapilar/azizpavlus_kilisesi2.jpg",
    image3:"/src/assets/tarihi_yapilar/azizpavlus_kilisesi3.jpg",
    image4:"/src/assets/tarihi_yapilar/azizpavlus_kilisesi4.jpg",
  },
  {
    id: "11",
    sub_category: "Tarihi Yapılar",
    sub_category_name: "tarihi_yapilar",
    title: "Kilistra Haçlı (Kaya) Kilise",
    path: "kilistra_kilise",
    cover_image:"/src/assets/tarihi_yapilar/kilistra_kilise1.jpg",
    description:
      "Günümüzde Konya’nın Meram ilçesine bağlı Hatunsaray beldesinde yer alan Kilistra antik kenti, içerisinde barındırdığı kilise hasebiyle Erken ve Orta Dönem Hristiyan tarihi açısından yüksek bir öneme sahiptir. Şehir, kuruluşu itibariyle Roma askeri üssü olarak planlandıysa da sonraki yıllarda, özellikle Aziz Pavlus ve Barnabas’ın Konya’dan kaçarak Lystra’ya gelip tebliğe başlamasının ardından, artan Hristiyan nüfus sebebiyle kilise ve mabetlerle dolmuştur. Antik kentte yer alan pek çok kilise arasında en önemlilerden bir tanesi Haç Planlı Şapel ve Sandıkkaya adlarıyla da bilinen olarak Haçlı Kilise’dir.",
    image1:"/src/assets/tarihi_yapilar/kilistra_kilise1.jpg",
    image2:"/src/assets/tarihi_yapilar/kilistra_kilise2.jpg",
    image3:"/src/assets/tarihi_yapilar/kilistra_kilise3.jpg",
    image4:"/src/assets/tarihi_yapilar/kilistra_kilise4.jpg",
  },
  {
    id: "12",
    sub_category: "Tarihi Yapılar",
    sub_category_name: "tarihi_yapilar",
    title: "Augustos Oteli",
    path: "augustos_oteli",
    cover_image:"/src/assets/tarihi_yapilar/augustos_oteli1.jpg",
    description:
      "Konya Tren Garı’nın doğusunda, yolun karşısın­da Barok stilinde Avrupa Mimarisi’nin izlerini taşıyan tarihî bir yapı gözünüze çarpacaktır. Özgün haliyle Augustos Oteli adını taşıyan bina İstanbul-Bağdat Demiryolu’nun Konya’ya ulaşması ile birlikte şehrin Rum zenginlerinden olan Augustos Efendi tarafından 1895 yılında yaptırılmıştır. Bir süre Askeri Ulaştırma Okulu olarak hizmet veren bina, bir dönem de PTT binası olarak kullanılmıştır. 1982 yılında Anıtlar Yüksek Kurulu tarafından tescil edilen yapı, nihayet 2012 yılında Meram Belediyesi tarafından aslına uygun olarak restore edilmiş ve Augustos Butik Otel asıyla yeniden hizmete açılmıştır. Augustus Butik Hotel 5 yıllık bir serüvenden sonra 25 Mayıs 2017’de tarihe karışarak “Şehrin Tasarım Atölyesi” haline dönüştürülmüştür.",
    image1:"/src/assets/tarihi_yapilar/augustos_oteli1.jpg",
    image2:"/src/assets/tarihi_yapilar/augustos_oteli2.jpg",
    image3:"/src/assets/tarihi_yapilar/augustos_oteli3.jpg",
    image4:"/src/assets/tarihi_yapilar/augustos_oteli4.jpg",
  },
  {
    id: "13",
    sub_category: "Camiler, Medreseler ve Türbeler",
    sub_category_name: "camiler",
    title: "İplikçi Cami",
    path: "iplikci_cami",
    cover_image:"/src/assets/camiler/iplikci_cami1.jpg",
    description:
      "Konya’nın dillere destan Alâeddin Tepesi’nin hemen doğusunda yer alan ve kimileri tarafından Ebulfazl Mescidi olarak da adlandırılan İplikçi Cami’nin tarihi 13. yüzyıla dayanmaktadır. Önceleri daha küçük bir arazi üzerinde konumlanan cami, zaman içerisinde genişletilerek bugünkü şeklini almıştır. Eserin inşa kitâbesi bulunmamakla birlikte, çeşitli tarihi kaynaklar, Mevlâna Celalettin Rûmi’nin daha önce burada vaaz ettiğini göstermektedir. Son olarak 1945 yılında Müzeler Müdürlüğü tarafından onarım gören cami, bir süreliğine Konya Müzesi Klasik Eserler Bölümü olarak hizmet vermiş, daha sonra yeniden camiye dönüştürülmüştür. Tarihler boyunca gerçekleştirilen yol ve kaldırım çalışmaları neticesinde çukurda kalan yapının minare kaidesi ve cephe duvarları restore edilerek genişletilmiştir.",
    image1:"/src/assets/camiler/iplikci_cami1.jpg",
    image2:"/src/assets/camiler/iplikci_cami2.jpg",
    image3:"/src/assets/camiler/iplikci_cami3.jpg",
    image4:"/src/assets/camiler/iplikci_cami4.jpg",
  },
  {
    id: "14",
    sub_category: "Camiler, Medreseler ve Türbeler",
    sub_category_name: "camiler",
    title: "Sahip Ata Camii ve Külliyesi",
    path: "sahip_ata_camii",
    cover_image:"/src/assets/camiler/sahip_ata_camii1.jpg",
    description:
      "Câmi, en eski Selçuklu eserlerinden olup, Alâaddin Tepesi üzerinde inşa edilmiştir. Selçuklu Sultanı I. Rükneddin Mesud (1116-1156) zamanında yapımına başlanmış ve I. Alâaddin Keykubad zamanında tamamlanmıştır (1221). Câmi avlusunda I. Mesud, Kılıç Arslan, II. Rükneddin Süleyman, I. Gıyâseddin Keyhüsrev, I. Alâaddin Keykubad, II. Gıyâseddin Keyhüsrev, IV. Kılıç Arslan ve III. Gıyâseddin Keyhüsrev'in mezarları bulunmaktadır.",
    image1:"/src/assets/camiler/sahip_ata_camii1.jpg",
    image2:"/src/assets/camiler/sahip_ata_camii2.jpg",
    image3:"/src/assets/camiler/sahip_ata_camii3.jpg",
    image4:"/src/assets/camiler/sahip_ata_camii4.jpg",
  },
  {
    id: "15",
    sub_category: "Camiler, Medreseler ve Türbeler",
    sub_category_name: "camiler",
    title: "Kapu Cami",
    path: "kapu_cami",
    cover_image:"/src/assets/camiler/kapu-cami-1.jpg",
    description:
      "Konya'nın merkezinde Tevfikiye Caddesi üzerindedir. Asıl adı İhyaiyye olup eski Konya Kalesinin kapılarından birini çevresinde yer aldığında Kapu Camii adıyla anılır. Cami ilk defa 1658 yılında Mevlevi Dergahı Postnişinlerinden Pir Hüseyin Çelebi tarafından yapılmıştır. Bir süre sonra yıkılan bu camiyi 1811 yılında Konya Müftüsü Esenlilerlizade Seyyid Abdurrahman yenilemiş ancak 1867 yılında çıkan bir yangın cami ile birlikte bu civardaki vakıf dükkanlarını da yok etmiştir. Bu yeni inşasına dair 1285 H. (1868 M) tarihli kitabesi taç kapısı üzerinde yer almaktadır. Kapı Cami Konya'da yer alan Osmanlı Dönemine ait camilerinin en büyüğüdür. Kuzeyinde 10 mermer sütuna istinat eden yüksek bir son cemaat mahalli ve basık kemerli bir cümle kapısı vardır. Ayrıca doğu ve batı yönlerinde de birer kapısı bulunmaktadır. Kesme taşlardan inşa edilen camiin üzeri dıştan çatı, içten büyüklü küçüklü sekiz kubbe ile örtülüdür.",
    image1:"/src/assets/camiler/kapu-cami-1.jpg",
    image2:"/src/assets/camiler/kapu-cami-2.jpg",
    image3:"/src/assets/camiler/kapu-cami-3.jpg",
    image4:"/src/assets/camiler/kapu-cami-4.jpg",
  },
  {
    id: "22",
    sub_category: "Camiler, Medreseler ve Türbeler",
    sub_category_name: "camiler",
    title: "Ateşbazı Veli Türbesi",
    path: "atesbazi_veli_turbesi",
    cover_image:"/src/assets/camiler/atesbazi_veli_turbesi2.jpg",
    description: "Âteşbâz-ı Velî’nin türbesi Konya’da Meram yolu üzerinde Aşkan (Âşıkān “âşıklar”) tepesi yakınlarındadır. Selçuklu türbe mimarisinin özelliklerini taşıyan yapının muntazam kesme taştan inşa edilmiş gövde kısmı içeriden kare, dışarıdan sekizgen planlıdır. Üstü ise ehramî bir külâh ile örtülü olup Arapça kitâbesi güneydeki “niyaz penceresi”nin üzerindedir. Türbenin civarına, Sultan Veled’in kızı Arîfe Şeref Hatun’un oğlu Muzafferüddin Ahmed Paşa torunlarından Çelebi Abdüssamed tarafından bir zâviye yaptırılmış ve vakıflar kurulmuştur. Zamanla harap olan bu zâviyenin yerine bugünkü tekke, postnişin Vâhid Çelebi tarafından 1897 yılında inşa ettirilmiştir. Mevlevîlik’te mutfak “aşhane” olduğu gibi daha önemlisi, Mevlevîliğe intisap niyazında bulunan kişilerin temel eğitimlerinin yapıldığı yerdir. Mevlânâ zamanında bu önemli görevi “Âteşbâz-ı Velî” Yûsuf b. İzzeddin yerine getiriyordu. Sonraki dönemlerde bu unvan bu göreve tayin edilen kişiler için kullanılmıştır. Âteşbâz-ı Velî’nin türbesi Konya’da Meram yolu üzerinde Aşkan (Âşıkān “âşıklar”) tepesi yakınlarındadır. Selçuklu türbe mimarisinin özelliklerini taşıyan yapının muntazam kesme taştan inşa edilmiş gövde kısmı içeriden kare, dışarıdan sekizgen planlıdır. Üstü ise ehramî bir külâh ile örtülü olup Arapça kitâbesi güneydeki “niyaz penceresi”nin üzerindedir. Türbenin civarına, Sultan Veled’in kızı Arîfe Şeref Hatun’un oğlu Muzafferüddin Ahmed Paşa torunlarından Çelebi Abdüssamed tarafından bir zâviye yaptırılmış ve vakıflar kurulmuştur. Zamanla harap olan bu zâviyenin yerine bugünkü tekke, postnişin Vâhid Çelebi tarafından 1897 yılında inşa ettirilmiştir.",
    image1:"/src/assets/camiler/atesbazi_veli_turbesi1.jpg",
    image2:"/src/assets/camiler/atesbazi_veli_turbesi2.jpg",
    image3:"/src/assets/camiler/atesbazi_veli_turbesi3.jpg",
    image4:"/src/assets/camiler/atesbazi_veli_turbesi4.jpg",
  },
  {
    id: "16",
    sub_category: "Camiler, Medreseler ve Türbeler",
    sub_category_name: "camiler",
    title: "Sırçalı Medrese",
    path: "sircali_medrese",
    cover_image:"/src/assets/camiler/sircali_medrese4.jpg",
    description:
      "Sırçalı Medrese Selçuklu ve Osmanlı dönemlerinde medrese olarak kullanılmıştır. XVII. yüzyılda terk edilmiş olan medresenin talebe odaları yıkılmıştır. XIX. yüzyılda ise kerpiçle yapılan bu odalarda eğitime devam edilmiştir. Medrese 1954 yılında yeniden onarıma ve korumaya alınarak 1960 yılında Konya Müzesi’ne bağlı “Mezar Anıtları” bölümü olarak ziyarete açılmıştır. 1969 yılında Kültür Bakanlığı aslına uygun olarak Kültür Bakanlığı tarafından restore edilmiştir. 1988-1990 yılları arasında yeniden restorasyona alınan ve teşhir tanzimi yapılarak yenilenen müzenin bahçesinde toprak altında olan Bizans Devrine ait katakomp da onarılarak ziyarete açılmıştır. Sırçalı Medrese Mezar Anıtları Müzesi’nde çoğunluğu zaman içerisinde yok olan mezarlıklardan toplanan tarih ve sanat tarihi açısından değerli olan Selçuklu, Karamanoğlu ve Osmanlı Dönemlerine ait mezar taşları sergilenmektedir.",
    image1:"/src/assets/camiler/sircali_medrese1.jpg",
    image2:"/src/assets/camiler/sircali_medrese2.jpg",
    image3:"/src/assets/camiler/sircali_medrese3.jpg",
    image4:"/src/assets/camiler/sircali_medrese4.jpg",
  },
  {
    id: "17",
    sub_category: "Camiler, Medreseler ve Türbeler",
    sub_category_name: "camiler",
    title: "Tavus Baba Türbesi",
    path: "tavus_baba",
    cover_image:"/src/assets/camiler/tavus_baba1.jpg",
    description:
      "Konya'da Hz. Mevlânâ, Şems-i Tebrizi ve Şeyh Sadreddin Konevî türbelerinden sonra en fazla ziyaret edilen yerlerden biri de Meram'da bulunan Tavus Baba Türbesi'dir. Tavus Baba, Meram Çayı’na hâkim bir tepe üzerinde, Meram bağlarının yeşillikleri arasında sade, küçük ve mütevazı türbesinde asırlardır yatmaktadır. Uzun yıllardır gizemini koruyan Tavus Baba hakkında çeşitli rivayetler anlatılır. Her gün yüzlerce insan tarafından ziyaret edilen bu zatın kim olduğu, cinsiyeti ve hangi devirde yaşadığı hakkındaki rivayetler farklıllık gösterir. Türbede bulunan mermer kitabede Tavus Mehmet El-Hindi yazmakta, ancak doğum ve vefat tarihleri bilinmemektedir. Birkaç araştırmacıya göre memleketi Hindistan olan Tavus Baba, Selçuklu sultanlarından Rükneddin Süleyman ve Alâeddin Keykubat dönemlerinde Konya’da yaşamış Şeyh Tavus-ı Hindi adında bir evliyadır. Rivayete göre, Selçuklu sultanlarının kültür adamları ile tasavvuf erbabına gösterdikleri hürmetten dolayı Hindistan’dan uzun ve zahmetli bir yolculuk sonrasında gelip Konya’ya yerleşmiştir. Bu rivayetlerin aksine Ahmet Eflaki’nin “Ariflerin Menkıbeleri” adlı eserinde bu konuda ilginç bir hikâye anlatılır. Bu hikâyeden kaynaklı olmak üzere, halk arasında Tavus Baba namıyla meşhur kişi Konya’nın en büyük kadın evliyalarından biri olduğu anlatılır. Bu kadın tasavvuf ilmine sahip, ilim ve keramet sahibi tayy-i mekânla, dünya ve ötelere vakıf, Hz. Mevlânâ’nın özel olarak yetiştirdiği güzel bir insan olduğu rivayet edilir. Oldukça gizemli hikâyeleri nedeniyle Tavus Baba’nın Türbesi bilhassa yaz aylarında çokça ziyaret edilen yerlerin başında gelir.",
    image1:"/src/assets/camiler/tavus_baba1.jpg",
    image2:"/src/assets/camiler/tavus_baba1.jpg",
    image3:"/src/assets/camiler/tavus_baba1.jpg",
    image4:"/src/assets/camiler/tavus_baba1.jpg",
  },
  {
    id: "18",
    sub_category: "Camiler, Medreseler ve Türbeler",
    sub_category_name: "camiler",
    title: "Akçe Gizlenmez (Taş) Camii",
    path: "akce_gizlenmez_camii",
    cover_image:"/src/assets/camiler/akce_gizlenmez_camii1.jpg",
    description: "Türkiye Selçukluları Dönemi eseri olan Akçe Gizlenmez Camii, Aksinne Mahallesi Uzunharmanlar Caddesi üzerinde yer alır. Selçuklu Konya’sında Lârende Kapısı dışında, Sahip Ata Külliyesi’nin kuzeyinde bulunur. Kitabelerine göre, Selçuklu Sultanı İzzeddin Keykavus döneminde 1215 yılında, Hacı Ferruh Bin Abdullah tarafından Mimar Ramazan Bin Güneş’e yaptırılmıştır. Eserin içi, dışı, duvarları ve kubbesi bütünüyle Gödene ve Küçük Muhsine’den getirilen muntazam kesme taşlarla yapıldığından halk arasında Taş Camii olarak da adlandırılır. Bütünüyle kesme taştan inşa edilmiş olan yapı, Selçuklu taş işçiliğinin en güzel örneği olarak gösterilir. Banisinin adıyla Hacı Ferruh Cami olarak da bilinen yapı Vakıflar Genel Müdürlüğü tarafından 2006 yılında yapılan restorasyon kapsamında yenilenmiştir. Rivayete göre “Akçe Gizlenmez” adı yapının muntazam kesme taşlardan yapılması nedeniyle, taşların intizamını anlatmak için verilmiştir. Bu konuda halk arasında anlatılan hikâyeye göre caminin banisi Hacı Ferruh, inşaatı yapacağı zaman mimara şöyle demiştir: “Bana her tarafı taştan bir cami yapacaksın, taşlar birbirlerine o kadar intizamla yapıştırılmış ve kenetlenmiş olsun ki hiçbir yerine akça dahi gizlenmesin.” Nitekim hikâyeye göre camide kullanılan taşlar sanki aynı kalıptan dökülmüş gibi yekpare, öyle titizlikle hazırlanmış ve ahenkli bir şekilde yerleştirilmiş ki, hiçbir yerine akçe bile gizlenemezmiş. Gerçekten de Akçe Gizlenmez Cami, muntazam ve oldukça görkemli bir taş cepheye sahiptir.",
    image1:"/src/assets/camiler/akce_gizlenmez_camii1.jpg",
    image2:"/src/assets/camiler/akce_gizlenmez_camii2.jpg",
    image3:"/src/assets/camiler/akce_gizlenmez_camii3.jpg",
    image4:"/src/assets/camiler/akce_gizlenmez_camii4.jpg",
  },
  {
    id: "19",
    sub_category: "Müzeler",
    sub_category_name: "muze",
    title: "Konya Etnografya Müzesi",
    path: "konya_etnografya",
    cover_image:"/src/assets/muze/konya_etnografya1.jpg",
    description:
      "Alâeddin Tepesi’nin güneyinde Sahip Ata Vakıf Müzesi ile Arkeoloji Müzesi’nin bulunduğu cadde üzerinde 500 m kadar ilerlerseniz Konya Etnografya Müzesi’ne ulaşabilirsiniz. Müzedeki koleksiyonların çekirdeğini 1899 yılında kurulan Müze-i Hümayun Konya Şubesi ile Mevlâna Müzesi’nden devralınan etnografik eşyalar teşkil etmektedir. 1975 yılında Konya Etnografya Müzesi adıyla ziyarete açılan müze, zaman zaman Konya Türk-İslâm Sanatları Müzesi diye de anılmaktadır.",
    image1:"/src/assets/muze/konya_etnografya1.jpg",
    image2:"/src/assets/muze/konya_etnografya2.jpg",
    image3:"/src/assets/muze/konya_etnografya3.jpg",
    image4:"/src/assets/muze/konya_etnografya4.jpg",
  },
  {
    id: "20",
    sub_category: "Müzeler",
    sub_category_name: "muze",
    title: "Sahip Ata Vakıf Müzesi",
    path: "sahip_ata_vakif_muzesi",
    cover_image:"/src/assets/muze/sahip_ata1.jpg",
    description: "",
    image1: "/src/assets/muze/sahip_ata1.jpg",
    image2: "/src/assets/muze/sahip_ata2.jpg",
    image3: "/src/assets/muze/sahip_ata3.jpg",
    image4: "/src/assets/muze/sahip_ata4.jpg",
  },
  {
    id: "21",
    sub_category: "Müzeler",
    sub_category_name: "muze",
    title: "Atatürk Evi",
    path: "ataturk_evi",
    cover_image:"/src/assets/muze/ataturk_evi1.jpg",
    description:
      "Alaaddin Tepesi’nden Anıt Meydanı’na doğru giden yol üzerinde 300 m kadar ilerlerseniz, caddenin sağında bütün ihtişamıyla Avrupaî mimarinin etkilerini taşıyan bir yapı görürsünüz. Mimarî açıdan oldukça ilgi çekici olan iki katlı bu tarihî bina, XX. yüzyılın başlarında Konya’da yaşayan Marunîlerden Yusuf Şar isimli bir tüccar tarafından 1912 yılında konut olarak inşa edilmiştir. Muntazam kesme taş ve tuğladan inşa edilen yapı, 1923 yılında hazine adına tescil edilerek bu tarihten itibaren Vali Konağı olarak kullanılmış ve Gazi Mustafa Kemal’in Konya'ya yaptığı ziyaretlerde ona tahsis edilmiştir. Gazi Mustafa Kemal ilk olarak, Ankara'da TBMM’nin açılışından sonra 3 Ağustos 1920 tarihinde Konya'ya gelerek burada bir gece konaklamış ve Konyalılarla görüşmelerini gerçekleştirmiştir. Bu tarihten itibaren vefat edene kadar 12 defa Konya’ya gelen Gazi Mustafa Kemal, genellikle kendisine tahsis edilen bu iki katlı köşkte kalmayı tercih etmiştir. Hatta Gazi, 20 Mart 1923 tarihinden itibaren eşi Latife Hanım’la birlikte Konya’ya yapmış oldukları ziyarette 4 gün, 3 Ocak 1925’te başlayan ziyaretlerinde ise 11 gün bu köşkte konaklamışlardır. Müzedeki kayıtlara göre Gazi Mustafa Kemal, burada toplamda 53 gün konaklamıştır.",
    image1:"/src/assets/muze/ataturk_evi1.jpg",
    image2:"/src/assets/muze/ataturk_evi2.jpg",
    image3:"/src/assets/muze/ataturk_evi3.jpg",
    image4:"/src/assets/muze/ataturk_evi2.jpg",
  },
];
 